#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml>=6"]
# ///
"""
Extract GitHub usernames from a go-site users.yaml file.

Reads the YAML file (a top-level list of user records, each optionally
carrying `accounts.github`) and prints one GitHub username per line,
sorted, lowercased, and deduplicated, suitable as a JupyterHub
`allowed_users` allowlist.

Lowercasing matches the `LowercasedGitHubOAuthenticator` subclass in
`jupyterhub_config.py`, so the allowlist file and the spawned unix
accounts agree byte-for-byte.

Usage:
    scripts/extract_github_users.py path/to/go-site/metadata/users.yaml
    scripts/extract_github_users.py path/to/users.yaml | head

This script is invoked by cloud-init on the deployed instance to write
/etc/jupyterhub/github_allowed_users.txt at boot from a fresh fetch of
go-site users.yaml. Running it manually on a laptop is for ad-hoc
inspection only — no committed allowlist file is needed for production.

Self-bootstrapping via PEP 723 inline metadata: running it through
`uv run` (or directly if it's chmod +x) installs pyyaml into a
transient environment on first run.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

# Loose POSIX-username pattern, matching what jupyterhub_config.py will
# accept. Anything that fails this is silently dropped from the output
# with a stderr warning so the operator notices.
VALID = re.compile(r'^[a-z_][a-z0-9_-]{0,31}$')


def extract(path: Path) -> tuple[list[str], list[str]]:
    """Return (accepted, rejected) lists of GitHub usernames from a users.yaml."""
    with path.open() as f:
        data = yaml.safe_load(f)

    if not isinstance(data, list):
        raise SystemExit(f"{path}: expected a top-level list, got {type(data).__name__}")

    accepted: set[str] = set()
    rejected: list[tuple[str, str]] = []  # (name, reason)

    for entry in data:
        if not isinstance(entry, dict):
            continue
        accounts = entry.get('accounts') or {}
        gh = accounts.get('github')
        if not gh:
            continue
        if not isinstance(gh, str):
            rejected.append((repr(gh), 'not a string'))
            continue
        normalized = gh.strip().lower()
        if not normalized:
            rejected.append((gh, 'empty after strip/lower'))
            continue
        if not VALID.match(normalized):
            rejected.append((gh, f"normalized {normalized!r} fails POSIX-ish pattern"))
            continue
        accepted.add(normalized)

    return sorted(accepted), [f"{name}: {reason}" for name, reason in rejected]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.strip().split('\n')[0])
    parser.add_argument('users_yaml', type=Path,
                        help='Path to go-site/metadata/users.yaml')
    args = parser.parse_args()

    if not args.users_yaml.exists():
        print(f"error: {args.users_yaml} not found", file=sys.stderr)
        return 2

    accepted, rejected = extract(args.users_yaml)

    print(f"# Generated by scripts/extract_github_users.py from {args.users_yaml}")
    print(f"# {len(accepted)} GitHub usernames accepted, {len(rejected)} rejected")
    print("# Edit the source users.yaml in geneontology/go-site to change this list.")
    for name in accepted:
        print(name)

    if rejected:
        print(f"\n{len(rejected)} entries rejected:", file=sys.stderr)
        for line in rejected:
            print(f"  {line}", file=sys.stderr)

    return 0


if __name__ == '__main__':
    raise SystemExit(main())
